### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2737]
As discussed, we need to make a 3.0 release. Mainly to facilitate the new users of the 'code transformation' functionality and to emphasise that the API has changed since the 2.5.0 release.

 - [x] https://github.com/stfc/fparser/pull/451
 - [x] https://github.com/stfc/fparser/pull/450
 - [ ] #2701
 - [x] FFSL support is required (#2661)
 - [x] Document the OpenMP offload functionality (under https://psyclone.readthedocs.io/en/latest/transformations.html#openmp) and add/extend an LFRic example to show it.
 - [x] #2739 
 - [x] #2742 (PSyAD test-harness reproducibility)
 - [x] #2755 
 - [x] #2697 Would be nice to have as it also fixes NEMO integration tests.
 - [ ] Update version in Spack (and update Wiki to remind us to do this).
 - [x] #2766 Change index order for LFRic operators.
 - [x] #2795 Allow Fortran matmuls to take matrices with non-contiguous ranges.

We want this before SC24.

**Comment by hiker** [comment]
- [ ] #2694 
- [ ] #257

I might also consider #2483, that might be useful for work with the UM, but I need to check where this PR is exactly at

**Comment by LonelyCat124** [comment]
@arporter Should we rename the "nemo" tutorials to Code transformation before this release as well?

**Comment by arporter** [comment]
> @arporter Should we rename the "nemo" tutorials to Code transformation before this release as well?

Ideally, yes.

**Comment by LonelyCat124** [comment]
> > @arporter Should we rename the "nemo" tutorials to Code transformation before this release as well?
> 
> Ideally, yes.

I'll see if I can do this then

**Comment by hiker** [comment]
> > > @arporter Should we rename the "nemo" tutorials to Code transformation before this release as well?
> > 
> > 
> > Ideally, yes.
> 
> I'll see if I can do this then

#2759 (which I assume should go into 3.0 as well) addresses a similar issue with library files. And there are the examples as well.

We should agree on a name - maybe just `transformation`? Or `no_psykal`?

**Comment by sergisiso** [comment]
For the folder names: `generic` or `std_fortran` are other options.

**Comment by arporter** [comment]
Thanks @LonelyCat124 and @hiker. I like "generic" but am happy to go with the consensus.

**Comment by LonelyCat124** [comment]
I had a chat with Sergi about the tutorials and we decided to leave that until we have time to redo them entirely, as they're very out of date.

**Comment by arporter** [comment]
OK.

**Comment by hiker** [comment]
generic sounds fine to me

**Comment by hiker** [comment]
- [ ] #2790 (which is useful for training)  (should I perhaps move this up into the top level comment?)

**Comment by TeranIvy** [comment]
> We now have a hard deadline of 13th of December for this release. We should probably aim for at least a week earlier to allow for any unforeseen problems.

@arporter, it's Friday 13th of December for LFRic release to use PSyclone 3.0, which means we need to ideally be ready a week before that :)

**Comment by arporter** [comment]
The only thing outstanding now is #2701 (plus my small PR to update the OMP docs). Do you want to back-port your fix for this @sergisiso or shall we leave it?
@TeranIvy has the new, 'user-supplied kernels with operates-on dof' functionality been tested do you know?
We have CIUK from Weds to Fri next week so I would prefer to make the release on Monday or Tuesday if possible.

**Comment by arporter** [comment]
Release has been published on github and manually uploaded to pypi.
RTD has updated.
I've opened a PR on spack (https://github.com/spack/spack/pull/47964/files).
I'll email the LFRic list now!
