### ISSUE TITLE
[PSyIR] translate the algorithm layer to PSyIR

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#753]
The algorithm layer is currently parsed and transformed with fparser2. We should use the PSyIR instead for flexibility and to support potential future optimisations. The idea would be to parse to low level PSyIR then to recognise invoke regions, Kernels and arguments with particular types (fields, scalars, ...) and have domain-specific nodes for these. In the first instance we would need to be able to re-create the existing algorithm transformation performed by fparser2.

Once the above is working then additional functionality to try to determine the datatypes, function spaces etc. of algorithm arguments (within invokes) that passed into the PSy-layer. This could then be used to perform static correctness checks between algorithm fields and kernel arguments (specified with metadata).

This would complement issue #79.

**Comment by arporter** [comment]
This issue will also remove the limitations we currently have on the form of arguments that can be passed in an Invoke. (e.g. specifying a stencil depth as an integer literal with explicit kind fails.)

**Comment by rupertford** [comment]
PSyIR has made significant progress and is nearly at the stage where PSyclone could use the PSyIR to translate and analyse the algorithm layer. The following code parses simple examples:

```
from fparser.two.parser import ParserFactory
from fparser.common.readfortran import FortranFileReader
from psyclone.psyir.frontend.fparser2 import Fparser2Reader
from psyclone.psyir.backend.fortran import FortranWriter

# Parse code with fparser2
reader = FortranFileReader("alg.x90",
                           ignore_comments=True)
f2003_parser = ParserFactory().create(std="f2003")
parse_tree = f2003_parser(reader)

# Transform code from fparser2 to psyir
processor = Fparser2Reader()
name = "nonsense_alg"
container = processor.generate_container(parse_tree)
schedule = processor.generate_schedule(name, parse_tree, container=container)

# TODO transform from psyir to lfric algorithm psyir

# Take a look
container.view()

# TODO transform alg to processed alg

# print the transformed output
writer = FortranWriter()
code = writer(container)
print (code)
```

**Comment by rupertford** [comment]
Here is a list of known issues that need to be addressed/understood

1) calls are treated as codeblocks as the front-end does not yet parse them
2) Can we have a generic Fparser2Reader.generate() that just reads Fortran code, without the separate container and subroutine steps?
3) Seems to be a problem when leaving in comments
4) Test that code generated is correct for all LFRic algorithm files (run through this then parse again in the original way?)
5) Write psyir to lfric_algorithm_psyir transform
6) Transform algorithm invokes into their modified output
7) Integrate code into PSyclone (removing existing algorithm code (and classes - perhaps in two steps)

**Comment by rupertford** [comment]
![IMG_20210202_123400_resized_20210202_123525427](https://user-images.githubusercontent.com/7383165/106601917-29ed2e00-6554-11eb-8a5d-fbccbb336367.jpg)

**Comment by rupertford** [comment]
The above diagram is a summary of what we do at the moment for algorithm code and what I think we want to move to.

`Alg()` and `Alg().gen()` should be replaced with `fparser2psyir` and `psyir2alg`, with the Fortran backend generating the code.

The `FileInfo` class hierarchy that is produced by `parse` should be replaced with the `alg psyir` produced by `psyir2alg`. Note, an alternative to this would be to keep the `FileInfo` class hierarchy and add in any extra information that the PSy-layer might want e.g. datatypes, but I think the former is simpler and more powerful.

**Comment by rupertford** [comment]
Note the diagram above missed out a processing step (oops). alg.90 -> fparser2 ast -> psyir -> alg psyir -> processed alg psyir -> modified_alg.f90

**Comment by rupertford** [comment]
The first thing that is needed is a translation from `psyir -> alg psyir`. This requires new PSyIR subclasses to be created which provide at least as much information as the `FileInfo` hierarchy.

As fparser2 does not currently parse all invoke arguments correctly and the PSyIR does not support named arguments and structure constructors there has been a discussion about what the best way forward is. It has been agreed to continue with the original plan of translating from `fparser2algast -> psyir - alg psyir` which means that the translation from psyir to alg psyir will need to deal with information in code blocks and some incorrect psyir (structure constructors wrongly parsed as array references). This is OK as the psyir representation is not used anywhere else, it is just a stepping stone to alg psyir.

**Comment by rupertford** [comment]
Created branch [753_psyir_to_algpsyir](https://github.com/stfc/PSyclone/tree/753_psyir_to_algpsyir)

**Comment by rupertford** [comment]
Created branch [753_psyir_to_algpsyir](https://github.com/stfc/PSyclone/tree/753_psyir_to_algpsyir)

**Comment by rupertford** [comment]
The simple example provided in lfric (infrastructure/source/algorithm/dummy_alg_mod.x90) does not declare field_type. fparser2 does not check this so does not complain, but the PSyIR does. I've emailed @TeranIvy explaining the bug.

**Comment by rupertford** [comment]
There is another more fundamental problem that I had not thought about but is now obvious. LFRic supports the concept of builtins and when we declare a builtin in the algorithm code we do not say where it comes from (similar to Fortran intrinsics). However, this is not valid Fortran code. We get away with it with fparser2 as it does not currently check that symbols are declared (but will in the future). However, the PSyIR does check and rightly complains that builtin symbols are not declared.

Given that this is invalid Fortran, what I think we should do is add a use statement along the lines of:

```
use psyclone_builtins, only : setval_c
```

Of course, this use statement would need to be removed before outputting the processed algorithm code as they don't actually exist so we would get a compile error.

However, this would require a lot of LFRic code updating. For the timebeing I am thinking of injecting the above use statement (without the only clause) into the fparser2 ast. The problem with this temporary solution is that it means that all undeclared symbols won't raise an exception in the PSyIR as they could be declared in `psyclone_builtins`.

**Comment by rupertford** [comment]
The branch [753_psyir_to_algpsyir](https://github.com/stfc/PSyclone/tree/753_psyir_to_algpsyir) can now create basic algorithm psyir from psyir and psyir from an fparser2 ast for the algorithm layer. I had to do a number of hacks to do this so am going to spawn some additional issues to address these which I'll complete before continuing

**Comment by rupertford** [comment]
- [ ] PSyIR create methods should be classmethods not staticmethods (so subclasses can use them as expected)
- [ ] the fparser2 frontend should have a way of parsing containers containing routines in one go
- [ ] there should be a simple configurable way to specify the colour of a domain-specific psyir node
- [ ] find a useful way to implement the add_use utility (could be in fparser2?)

**Comment by rupertford** [comment]
We can now translate from a Fortran algorithm file to domain-specific PSyIR.

The next step is to produce processed PSyIR i.e. PSyIR that PSyclone outputs ready for compilation. This will replicate (and eventually replace) the `gen()` method in the `Alg` class within `alg_gen.py`.

**Comment by rupertford** [comment]
Created branch [753_process_alg_psyir](https://github.com/stfc/PSyclone/tree/753_process_alg_psyir)

**Comment by hiker** [comment]
Since #1202 has been closed (referring to this issue), I thought I just repeat it here:

I do indeed intend to add support for symbolic comparison as part of my work on the dependency analysis, see #1075 (my idea is to make sympy optional, since it comes with a large number of dependencies, numpy etc).

**Comment by sergisiso** [comment]
#1192 towards this issue has been merged and provide lowering to language level capabilities for the Algorithm layer concepts. Also it creates the interface symbols between the Algorithm and PSy layers, but there are still some unknowns about the order/steps to generate both layers.

**Comment by rupertford** [comment]
The next step will be to test the new Algorithm PSyIR approach with the gocean API

**Comment by rupertford** [comment]
Created branch [753_alg_psyir_gocean](https://github.com/stfc/PSyclone/tree/753_alg_psyir_gocean)

**Comment by rupertford** [comment]
Branch [753_alg_psyir_gocean](https://github.com/stfc/PSyclone/tree/753_alg_psyir_gocean) is ready to go on master in PR #1228 but needs to wait until PR #1234 is on master (as otherwise it will break PSyclone's support for the nemolite2d benchmark) which in turn is waiting on PR #1229 as that will hopefully fix some of the test failures in PR #1234.

In the mean time I have created branch [753_alg_psyir_lfric](https://github.com/stfc/PSyclone/tree/753_alg_psyir_lfric) which is a subbranch of [753_alg_psyir_gocean](https://github.com/stfc/PSyclone/tree/753_alg_psyir_gocean) and will let me test the algorithm PSyIR generation on LFRic algorithm code.

**Comment by rupertford** [comment]
At the moment the container and routine names produced by the algorithm layer will differ from the PSy-layer routine name if there is a name clash in the algorithm layer. This will be fixed when the Algorithm PSyIR is passed into the PSy-layer (as the PSy-layer will then determine the name from the PSyIR rather than working it out separately).

**Comment by sergisiso** [comment]
#1228 has been merged and now the GOcean API uses PSyIR in its Algorithm layer

**Comment by rupertford** [comment]
Next I need to restructure the generate.py code to call the psy generation after the algorithm generate for gocean1.0. Created branch [753_restructure_generate](https://github.com/stfc/PSyclone/tree/753_restructure_generate) to do this.

**Comment by rupertford** [comment]
Joerg has found some errors on master to do with pr #1228 so these need to be fixed.

In his example we get the following algorithm code:
```
...
use psy_time_step, only : combine_1, compute
      ...
      call compute(neighbours, current, born, die)
      call combine_1(current, die, born)
      ...
```

but the generated PSy-layer gives
```
  ...
  MODULE psy_time_step_alg_mod
    ...
    SUBROUTINE invoke_compute(neighbours, current, born, die)
    ...
    SUBROUTINE invoke_combine(current, die, born)
    ...
```

So there are 2 problems. 1) the module name is not the same and 2) the subroutine names are not the same.

Sergi has already looked at this and found the error:

"
The first issue is in src/psyclone/domain/common/algorithm/psyir.py:219 which should be:

```
nodes = self.root.walk((Routine, Container))
nodes = [node for node in nodes if not isinstance(node, FileContainer)]
```
​
And the second inconsistency is probably in the same file, I see that in `_def_routine_root_name` if there is a `name=` parameter we don't prefix it with `invoke_`. If I add `routine_root_name = f"invoke_{​​routine_root_name}​​"`  at line 183 then your example compiles
"

**Comment by rupertford** [comment]
Created branch [753_gocean_psyir_alg_error](https://github.com/stfc/PSyclone/tree/753_gocean_psyir_alg_error)

**Comment by rupertford** [comment]
The work in this issue has now been done so closing. New issues will capture using LFRic PSyIR, consistency between algorithm and psy-layer names and restructuring the PSy-layer
